### ISSUE TITLE
losing stack trace, anyway to retain it ?

### ISSUE THREAD

**Issue by appsolutegeek** [boltsource/apollo-errors#50]
Hi,

I am throwing a number of custom errors further up my project and these I generally would log before throwing, these are standard custom errors that inherit from the Error object in nodejs.

When I arrive at my resolver, I generally capture the error and throw an "apollo errors" Error but I lose the stack trace, the stack trace only has the entry of where I threw the new apollo error but nothing before it.

Do you know of a good solution or workaround ? I mean I could log the error before throwing the new apollo error but it would be great if it retained the stack trace

Here is what I am doing

```
  } catch (err) {
        switch (err.constructor) {
          case HttpBadRequestError:
            throw new BadRequestError()

          default:
            throw new InternalError()
        }
      }
```

The one above that is most important is the InternalError, this basically means it is an uncaught error.

here is my definition

```
import { createError } from 'apollo-errors'

export const InternalError = createError('InternalError', {
  message: 'An internal error has occurred'
})
```

As I say, throw the error here now removes all stacktrace from the previous error so all I know is that the code in the resolver threw an error but I have no reference to anything else.

I did try using longjohn - a node module for including longer stack traces, but I don't think this is the problem. 

Anybody managed to work around this ?

**Comment by AdelBachene** [comment]
I have the same issue

**Comment by AdelBachene** [comment]
I have the same problem eventhough adding the source error in the internalData and data
>            data: {
>                 sourceMessage: (error.message) ? error.message : "",
>                 sourceStatusCode: (error.code) ? error.code : ""
>             },
>             internalData: {
>                 sourceError: error
>             }

I could still see it in all catches but I lost when it arrives at  format error Im able to see the message only

>         graphqlExpress((req) => 
>                      ({
>                         schema: schema,
>                         context: {
>                             req: req
>                         },
>                         formatError: (error) => {
>                             console.log("+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*");
>                             console.dir(error);
>                             console.log("+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*+=-_*");
>                             return error;
>                 },
>                         debug: true,
>                         tracing: true,
>                         cacheControl: false
>                     })
>             )

**Comment by thebigredgeek** [comment]
@appsolutegeek are you using schema stitching as well?

**Comment by appsolutegeek** [comment]
no, I used another library to merge my schema...

**Comment by codegoblin** [comment]
@thebigredgeek I am also curious how one should go about solving this problem. Let's say my model layer is calling a connector and that connector throws an error. What's the proposed way to bubble up that original error's stacktrace to the graphql response's errors array? If you use an ApolloError in the resolver to mask the original connector error, it would seem that the returned stacktrace is pointing to the resolver error rather than the original trouble spot in the connector.

**Comment by thebigredgeek** [comment]
PRs welcome on this.  Closing for now
