### ISSUE TITLE
apollo-errors vs apollo-server built in ApolloError?

### ISSUE THREAD

**Issue by marcusx** [boltsource/apollo-errors#55]
Can you describe the advantage/difference using apollo-errors compared to 
https://www.apollographql.com/docs/apollo-server/features/errors.html#Other-errors that are described in the apollo-server docs?

**Comment by zenVentzi** [comment]
Hi @marcusx , did you figure it out? I've been wondering about the same thing as well

**Comment by thebigredgeek** [comment]
TBH they are pretty similar.  Apollo added similar functionality in 2.0, and has said it was heavily inspired by this package.  In pre-1.0 and 1.x, there was no such functionality.
